config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "books#index"

  resources :books, only: [:index, :show]

  resource :user

  namespace :account do

    resources :books do
      member do
        post :publish
        post :hide
      end
    end

    resources :users do
      resource :profile, :controller => "user_profiles"
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true

  belongs_to :user

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  scope :published, -> { where(is_hidden:false) }
  scope :recent, -> { order('created_at DESC') }

  mount_uploader :image, ImageUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  has_one :profile

  accepts_nested_attributes_for :profile
end

app/controllers/account/books_controller.rb
class Account::BooksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :find_book_and_check, only: [:edit, :update, :destroy, :publish, :hide]

  def index
    @books = current_user.books.recent
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user

    if @book.save
      flash[:notice] = "新建成功"
      redirect_to account_books_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "完成修改"
      redirect_to account_books_path
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to accounts_books_path
    flash[:alert] = "已删除#{@book.title}"
  end

  def publish
    @book.publish!
    redirect_to :back
    flash[:notice] = "已公开#{@book.title}"
  end

  def hide
    @book.hide!
    redirect_to :back
    flash[:notice] = "已隐藏#{@book.title}"
  end

  private

  def find_book_and_check
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to root_path
      flash[:alert] = "You have no permission."
    end
  end

  def book_params
    params.require(:book).permit(:title, :description, :is_hidden, :image, :author, :publisher, :price, :isbn)
  end

end

app/controllers/account/user_profiles_controller.rb
class Account::UserProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user_and_profile

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to account_users_path
      else
        render "edit"
      end
    end

    protected

    def find_user_and_profile
      @user = User.find(params[:user_id])
      # 因为新建的用户并没有 profile，所以这里先检查是否有 @user.profile，如果没有的话就用 @user.create_profile 新建进数据库
      @profile = @user.profile || @user.create_profile
    end

    def profile_params
      params.require(:profile).permit(:legal_name, :birthday, :location, :occupation, :bio, :wechat_id, :weibo_id, :image)
    end

end

app/controllers/account/users_controller.rb
class Account::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to account_users_path
    else
      render "edit"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.published.recent
  end

  def show
    @book = Book.find(params[:id])
    if @book.is_hidden
      flash[:warning] = "This Book already archieved"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def show
  end

  def edit
  end

  def update
    if @user != current_user
      redirect_to account_users_path
      flash[:alert] = "这是别人的主页哦😉"
    end

    if @user.update(user_params)
      flash[:notice] = "修改成功"
      redirect_to edit_user_path
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:profile_attributes => [:id, :legal_name, :birthday, :location, :occupation, :bio, :wechat_id, :weibo_id, :image])
  end

  def find_user
    @user = current_user
    @user.create_profile unless @user.profile
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "おはいよ"
  end
end

app/helpers/account/books_helper.rb
module Account::BooksHelper
  def render_book_status(book)
    if book.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/helpers/account/user_profiles_helper.rb
module Account::UserProfilesHelper
end

app/helpers/account/users_helper.rb
module Account::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

  def render_book_author(book)
    if book.author.nil?
      book.author = "未填写"
    else
      book.author
    end
  end

  def render_book_publisher(book)
    if book.publisher.nil?
      book.publisher = "未填写"
    else
      book.publisher
    end
  end

  def render_book_price(book)
    if book.price.nil?
      book.price = "0.00"
    else
      book.price
    end
  end

end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/index.html.erb
<div class="pull-right">
  <%= link_to(t('New Book'), new_account_book_path, class: "btn btn-primary") %>
</div>
<br><br>

<% @books.each do |book| %>
  <div class="card-surface">
    <div class='col-xs-12 col-sm-6 col-md-4 col-lg-2'>
        <div class="card">
          <div class="col-xs-12 col-sm-6 col-md-6">
              <div class="card-topper">
                  <% if book.image.present? %>
                    <%= image_tag(book.image.thumb.url, class: "book-img") %>
                  <% else %>
                    <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "book-img") %>
                  <% end %>
              </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="card-block">
              <h4 class="card-title"><%= t("book.title", :name => book.title) %></h4>
              <h6><%= t("author") %>: <%= render_book_author(book) %></h6>
              <h6><%= t("Owner") %>: <%= book.user.email %></h6>
              <p class="card-text"><%= t("publisher") %>:<%= render_book_publisher(book) %></p>
              <h6 class="published-date">
                <%= book.updated_at.to_s(:ymdh) %>
                <label class= "label label-lg label-success">Statu</label>
              </h6>

                <h5 class="visible-xs-block btn-group">
                  <%= link_to("详情", book_path(book), class: "btn btn-info btn-xs") %>
                  <%= link_to("借阅", "#", class: "btn btn-success btn-xs") %>
                </h5>
            </div>
          </div>
        </div>
        <div class="middle">
          <%= link_to("详情", book_path(book), class: "btn btn-info") %>
          <%= link_to("借阅", "#", class: "btn btn-success") %>
        </div>
    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-6 col-sm-12 col-xs-12">
    <% if @book.image.present? %>
      <%= image_tag(@book.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12">
    <h3>
      <%= t("book.title", :name => @book.title) %>
      <label class= "label label-lg label-success">Statu</label>
    </h3>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12">
    <h4>
      <%= t("author") %>：
      <%= render_book_author(@book) %>
    </h4>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12">
    <p>
      <%= t("publisher") %>：
      <%= render_book_publisher(@book) %>
    </p>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12 published-date">
    <%= @book.updated_at.to_s(:ymdh) %>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12">
    <p>
      <%= t("price") %>：
      <%= render_book_price(@book) %>
    </p>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12" style="height:100px;">
      <p>
        <%= t("description") %>
        <%= simple_format(@book.description) %>
      </p>
  </div>
</div>

<% if current_user && current_user == @book.user %>
  <div class="pull-right">
    <div class="col-md-6 col-sm-6 col-xs-12" style="height:100px;">
      <div class="btn-group-vertical" role="group" aria-label="Basic example">
        <%= link_to(t("Edit"), edit_account_book_path(@book), class: "btn btn-primary") %>
        <%= link_to(t("Delete"), account_book_path(@book), method: :delete, :date => { :confirm => "Are you sure?"}, class: "btn btn-danger") %>

        <% if @book.is_hidden %>
          <%= link_to(t("Hide"), publish_account_book_path(@book), method: :post, class: "btn btn-success") %>
        <% else %>
          <%= link_to(t("Publish"), hide_account_book_path(@book), method: :post, class: "btn btn-info") %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2018 BooK Flow
        <br>Design by
        <a href="https://jaygjianguo.github.io/" target=_new>Jaykey</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!--- Include the above in your HEAD tag ---------->


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#toggle-dorpdown-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">图书漂流</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="toggle-dorpdown-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to("我的图书", account_books_path, class: "fa fa-book ") %>
        </li>
        <li>
          <%= link_to("书友档案", account_users_path, class: "fa fa-address-card") %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
            <li><%= link_to(content_tag(:i, "注册", class: "fa fa-sign-in"), new_user_registration_path)%></li>
            <li><%= link_to(content_tag(:i, "登录", class: 'fa fa-address-card'), new_user_session_path) %></li>
        <% else %>
          <li>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-user-circle" aria-hidden="true">
                  Hi!, <%= current_user.email %>
                </i>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to("个人主页", user_path) %></li>                <li class="divider"></li>
                <li> <%= link_to(content_tag(:i, "登出", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete) %> </li>
              </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>图书漂流</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render "common/navbar" %>
    <%= render "common/flashes" %>
    <div class="container-fluid">
      <%= yield %>
    </div>

    <%= render "common/footer" %>
  </body>
</html>

app/views/users/edit.html.erb
<h2><%= t("Edit User") %></h2>

<%= simple_form_for @user do |f| %>

  <%= f.simple_fields_for :profile do |ff| %>

  <%= ff.input :legal_name, label: t("Legal Name") %>

  <%= t("Birthday") %> <br>
  <%= ff.date_select :birthday, start_year: Date.today.year - 7,
                            end_year: Date.today.year - 100,
                            order: [:year, :month, :day], label: false %>

  <%= ff.input :location, label: t("Location") %>
  <%= ff.input :occupation, label: t("Occupation") %>
  <%= ff.input :bio, label: t("Bio") %>
  <%= ff.input :wechat_id, label: t("Wechat") %>
  <%= ff.input :weibo_id, label: t("Weibo") %>

  <% if @user.profile.image.present? %>
    <span>目前头像</span><br>
    <%= image_tag(@user.profile.image.thumb.url) %>
  <% end %>

  <%= ff.input :image, as: :file, label: t("User Image") %>

  <% end %>

  <%= f.submit "Save", label: t("Save"), :class => "btn btn-primary" %>

<% end %>

app/views/users/show.html.erb
<div class="content" id="about-header">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
      <div>
        <% if @user.profile.image.present? %>
          <%= image_tag(@user.profile.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
        <% end %>
      </div>
      <div class="text-center">
        <h2><%= @user.profile.legal_name %></h2>
        <p><%= @user.profile.bio %></p>
      </div>
    </div>
  </div>
  <!--正文-->
  <div class="row" id="offer">
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
      <div class="work-experience">
        <h3 class="title">生日</h3>
        <p>
          <%= @user.profile.birthday %>
        </p>
        <div class="body-section">
          <ul>
            <li><%= @user.profile.location %></li>
            <li><%= @user.profile.occupation %></li>
          </ul>
        </div>
      </div>
      <div class="contact-show">
        <h3 class="title ">
          <span class="glyphicon glyphicon-earphone"></span>
          联系我</h3>
        <p>
          微信 :
          <%= @user.profile.wechat_id %>
        </p>
        <p>
          微博 :
          <%= @user.profile.weibo_id %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <%= link_to(t("Edit User"), edit_user_path, class: "btn btn-primary pull-right") %>
</div>

app/views/welcome/index.html.erb
<h1>Hello 2018!</h1>